name: Mirror to GitLab
on: [push, delete, create]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.upc.edu:upcxels1/minimumviabledataspace.git"
          git push gitlab --mirror
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
